spring:
    application:
        name: financetrackingbackend
    security:
        enabled: false
        user:
            name: admin
            password: admin
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false

logging:
    level:
        root: INFO
        com.financetrackingbackend: INFO

test:
    value: docker

external:
    services:
        ulsterbank:
            base-url: ${wiremock-host}
            accounts-url: open-banking/v3.1/aisp/accounts
            auth-url: https://api.sandbox.ulsterbank.co.uk/authorize
            redirect-url: ${app-host}/ulsterbank/oauth/callback.html
            client-id: ${ULSTERBANK_CLIENT_ID}
            client-secret: ${ULSTERBANK_CLIENT_SECRET}
        monzo:
            base-url: ${wiremock-host}
            auth-url: ${wiremock-host}
            redirect-url: ${app-host}/monzo/oauth/callback
            client-id: ${MONZO_CLIENT_ID}
            client-secret: ${MONZO_CLIENT_SECRET}

aws:
    dynamodb:
        endpoint: ${wiremock-host}
        region: eu-west-1
        access-key: test
        secret-key: test

wiremock-host: http://localhost:1080
app-host: http://localhost:8080