name: Deploy Swagger UI to Pages

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Swagger UI
        run: npm install -g swagger-ui-dist
      - name: Prepare Swagger UI
        run: |
          mkdir -p swagger-ui
          cp financetrackingbackend/openapi.yaml swagger-ui/openapi.yaml
          cp -r $(npm root -g)/swagger-ui-dist/* swagger-ui/
          sed -i 's|https://petstore.swagger.io/v2/swagger.json|./openapi.yaml|' swagger-ui/swagger-initializer.js
          sed -i 's|<title>Swagger UI</title>|<title>Finance Tracking API Spec</title>|' swagger-ui/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './swagger-ui'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4